# This workflow verifies the code coverage minimum is met
name: Coverage Verification
permissions:
  contents: read
on:
  workflow_call:
jobs:
  coverage-verification:
    runs-on: ubuntu-latest
    name: Coverage Verification
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Verify Coverage
      run: ./gradlew jacocoTestCoverageVerification --warn --no-daemon
      timeout-minutes: 4
